# Generated by Django 4.2.8 on 2024-05-20 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IMaster', '0003_topic_studentcourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
