# Generated by Django 4.2.8 on 2024-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMaster', '0004_course_enrolled_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(related_name='courses', to='IMaster.topic'),
        ),
    ]
